version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: collabdesk_backend
    ports:
      - "5713:5713"
    environment:
      - REDIS_HOST=redis
    env_file:
      - .env
    depends_on:
      - redis
    volumes:
      - .:/app
       

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  node_modules: