export class workspaceEnity{
    id:string;
    name:string;
    ownerId:string;
    directories:{Did:string,Dname:string}[];
    userDetails:{uId:string,email:string}[];
    meetingRoom:string;
    type:string;
    trashId:string|null
    constructor(
        id:string,
        name:string,
        ownerId:string,
        directories:{Did:string,Dname:string}[],
        userDetails:{uId:string,email:string}[],
        meetingRoom:string,
        type:string,
        trashId:string|null,
    )
    {
       
       this.id=id;
       this.name=name;
       this.ownerId=ownerId;
       this.directories=directories;
       this.userDetails=userDetails;
       this.meetingRoom=meetingRoom;
       this.type=type;
       this.trashId=trashId;
    }
}